### ISSUE TITLE
Surface Pro 4

### ISSUE THREAD

**Issue by sahaskatta** [Microsoft/3-in-1-dock#1]
Any chance you can release a new version to accommodate the thinner frame of the Surface Pro 4?

**Comment by danchar4** [comment]
sahaskatta, we are working on a new version that will accommodate both the Surface Pro 3 and Surface Pro 4 and use the new MS brick-shaped dock rather than the clamp-style dock.

In the meantime, it is trivial to modify the current "cradle" part with a Dremel tool to fit the SP4.

**Comment by danchar4** [comment]
OK I finally checked in the design files for the SP4-style dock into a new branch. This version will accommodate the Surface Pro 3, Surface Pro 4 and uses the new brick-shaped dock instead of the old clamp-style dock. Sorry no build guide yet.... 

https://github.com/Microsoft/3-in-1-dock/tree/danchar4-patch-1/SP4Dock
https://blogs.msdn.microsoft.com/danchar/2016/05/03/sneak-preview-of-sp4-dock/
